import numpy as np

In [3]:
import numpy as np

In [4]:
# this library is used for numerical computations 
# numpy defines its own data types suc ha s np.int64 , np.int32 , np .float 64 etc 

In [5]:
# declaring arrrays 
# function call is np.array()
# the dimensions are stored iun shape()
x = np.array([1,2,3,5], dtype="float32")
print(x)
print(x[3])
print(x.shape)


[1. 2. 3. 5.]
5.0
(4,)


In [6]:
# two dimensional array accessed using list of lists
z = np.array([[1,2,3],[4,5,6]])
print(z)
print(z.shape)
print(z[1,1]) #5

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [40]:
#three dimensional array returns the shape method as tuples
#
#

In [8]:
#evenly spaced one dimensional array 
g = np.linspace(-2,2,9)
#start -2 till 2 9 values 
print(g)

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]


In [9]:
# 1d array of random numbers 
e = np.random.normal(10,100,10)
print(e)

[ 119.61623078   59.36619755 -143.52787632  -98.73548571   26.29077686
  -49.36683823   44.98150222 -102.06114108   41.49140876  -27.09955483]


In [10]:
# provided shape create bull array
shape = (2,3)
i = np.zeros(shape)
print(i)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:

m=np.ones((2,3))
print(m)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# the shape attribute is a tuple 
print(m.shape[0],m.shape[1])

2 3


In [16]:
        #reshaping a numpy array 
j = np.array([[1,3,4]])
#ravel funcion converts multidimentional array into single dimension 
j1D = j.ravel()
print(j)
print(j1D)


[[1 3 4]]
[1 3 4]


In [17]:
#reshape function also does the same 
j2= j.reshape(3,)
print(j2)

[1 3 4]


In [19]:
#operations on numpy arrays 
#addition of two arrays of same dimensions 
g1= np.array([[1,1,1],[2,2,2],[3,3,3]])
g2= np.array([[0,0,0],[1,1,1],[2,2,2]])
g3 = g1+g2 #[[1,1,1],[3,3,3],[5,5,5]]
print(g3)

[[1 1 1]
 [3 3 3]
 [5 5 5]]


In [21]:
# sqrt function 
g4 = np.sqrt(g1)
print(g4)

[[1.         1.         1.        ]
 [1.41421356 1.41421356 1.41421356]
 [1.73205081 1.73205081 1.73205081]]


In [22]:
#min and max values 
print(g1.max())
print(g2.min())
print(g1.sum())

3
0
18


In [23]:

g6 = np.arange(10) #arange prints a one dimensional array from 0 to n-1
print(g6)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
#mean median mode 
#The mean gives the arithmetic mean of the input values.
#The median gives the middle values in the given array. Its syntax is given by np.median().
#The standard deviation gives us the spread of distribution of array values. Standard deviation is given by the syntax np.std() or numpy.std().
#Use the SciPy mode() method to find the number that appears the most:
print(np.mean(g6))
print(np.median(g6))
print(np.std(g6))



4.5
4.5
2.8722813232690143


In [31]:
# computing along each dimension 
#axis =1 rows 
# axis 2 = columns 
print(np.sum(g1,axis=1))


[3 6 9]


In [33]:
#matrix multiploication and matrix inverse 
#for inverse : square matrix hon achahiye ie shape(x,x)
#np.matmul for multipliction 
g11= np.array([[1,2],[1,2],[3,4]])  #shape(3,2)
g12 = np.array([[1,2,3],[3,4,5]])  #shape(2,3)
g13 = np.matmul(g11,g12)
print(g13) # shape 3,3


[[ 7 10 13]
 [ 7 10 13]
 [15 22 29]]


In [35]:
#inverse 
zinv = np.linalg.det(g13)
print(zinv)
#identity matrix 
#print(np.matmul(g13,zinv)) # determinant is zero so inverse in sot possible as its a single matrix


0.0


In [37]:
# transpose 
print(g13.transpose())

[[ 7  7 15]
 [10 10 22]
 [13 13 29]]


In [39]:
# conjugate 
print(g13.conjugate())

[[ 7 10 13]
 [ 7 10 13]
 [15 22 29]]
